### ISSUE TITLE
请问什么时候公开论文代码

### ISSUE THREAD

**Issue by stack-heap-overflow** [lbe0613/GCC#1]
作者你好，拜读了这篇论文，个人认为使用偏旁部首加入编码的思路比较有意思。但是其中涉及较多细节，希望能参考代码实现来理解。该仓库已经空置两个月，请问什么时候能上传相关代码。期望得到回复，非常感谢！

**Comment by lbe0613** [comment]
您好，代码和模型已更新，感谢您的关注！
